name: GitHub Pages deploy

on:
  push:
    branches: [deploy-testing]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Cleaning dist directory
        run: sudo rm -rf dist

      - name: Installing my packages
        run: npm ci

      - name: Build my App
        run: npm run build && touch ./dist/.nojekyll

      - name: Clean up previous deployment
        run: |
          git worktree prune
          rm -rf .git/worktrees/github-pages-deploy-action-temp-deployment-folder/

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy-testing # The branch the action should deploy to.
          folder: dist # The folder the action should deploy to.
